compare_all_histories: compare_all_histories.cc strain2spline.h
	g++ -std=c++11 -Wall -lm compare_all_histories.cc -o compare_all_histories

test_strain2spline: test_strain2spline.cc strain2spline.h
	g++ -Wall -lm test_strain2spline.cc -o test_strain2spline
